.travis.yml
package.json
package.sh

Add travis files

---

CHANGELOG.md
README.md
package.json

Full diff https://github.com/TransbankDevelopers/transbank-pos-sdk-web-js/compare/1.2.0...chore/prepare-release-2.0

Prepare release 2.0

---

package-lock.json
package.json

Update dependencies to fix security alerts

Update dependencies to fix security alerts

---

CHANGELOG.md
README.md

Full diff https://github.com/TransbankDevelopers/transbank-pos-sdk-web-js/compare/2.1.0...chore/prepare-release-2.2.0

Prepare release 2.2.0

---

babel.config.json
package.json
package.sh
src/pos.js
webpack.config.js

Fix babel configuration. Now it should work on IE10

Fix babel configuration

---

.gitignore
.travis.yml
package-lock.json
package.json
package.sh

Fix travis deployment and configuration

Fix travis deployment and configuration

---

CHANGELOG.md

Full diff https://github.com/TransbankDevelopers/transbank-pos-sdk-web-js/compare/2.2.0...chore/prepare-release-2.2.1

Prepare release 2.2.1

---

.npmignore

Fix npmignore

---

src/pos.js

Fix load keys name adding an alias to the incorrect named function

Fix load keys name adding an alias to the incorrect named function

---

src/pos.js

poll function

---

src/pos.js

Solved problem with isConnected variable always true

Add events for connect and disconnect

---

package.json
src/pos.js

Solved double request issue and print flag issue. Verification of the versions of the web SDK and the web agent is added

Problem in response on double request

---

CHANGELOG.md
package.json

You can see full diff here: https://github.com/TransbankDevelopers/transbank-pos-sdk-web-js/compare/2.2.1...chore/prepare-release-3.0.0

Prepare release 3.0.0

---

README.md

Add info for deployment

---

src/pos.js

Events are added for when the socket or port is connected and disconnected

Add events for port and socket connection

---

package-lock.json
package.json
src/pos.js

Warning and version checker deleted

Delete version checker

---

src/pos.js

Add baudrate option to autoconnect and openPort

---

CHANGELOG.md

You can see full diff here: https://github.com/TransbankDevelopers/transbank-pos-sdk-web-js/compare/3.1.0...chore/prepare-release-3.1.1

Prepare release 3.1.1

---

README.md

Update agent reference link to the correct repository

Update agent reference link

---

index.html
webpack.config.js

fix some kiuwan reports:
Move pos script on example head
remove unnecesary comma

fix: kiuwan reports

---

CHANGELOG.md

chore: prepare release 4.0.0

---

.github/workflows/build.yml
package-lock.json
package.json
webpack.config.js

Update webpack version for node 20 compatibility

chore: update webpack

---

src/pos.js

This PR improves the connection flow, preventing false connection status.

feat: improve connection flow

---

package.json

This PR update module configuration

chore: update module configuration

---

src/pos.js

This PR improve the disconnection flow when there is no previous connection.

feat: improve disconnect flow

---

package-lock.json
package.json
src/pos.js

chore: update dependencies

---

src/pos.js
webpack.config.js

This PR fix the kiuwan alerts.

fix: kiuwan report 

---

CHANGELOG.md
README.md
package.json

chore: prepare release 5.0.0

---

.npmignore
CHANGELOG.md
README.md
package-lock.json
package.json

Release version 5.0.1
Full Diff: https://github.com/TransbankDevelopers/transbank-pos-sdk-web-js/compare/master...chore/prepare-release-5.0.1

chore: prepare release 5.0.1
